### ISSUE TITLE
Implement the use case in Java Script - Compare two version numbers version1 and version2.

### ISSUE THREAD

**Issue by rajlearner17** [anupsingh0512/Dice_game#1]
If version1 > version2 return 1; if version1 < version2 return -1;otherwise return 0.
You may assume that the version strings are non-empty and contain only digits and the . character.
The . character does not represent a decimal point and is used to separate number sequences.
For instance, 2.5 is not "two and a half" or "half way to version three", it is the fifth second-level revision of the second first-level revision.
You may assume the default revision number for each level of a version number to be 0. For example, version number 3.4 has a revision number of 3 and 4 for its first and second level revision number. Its third and fourth level revision number are both 0.

Example 1:
Input: version 1 = "0.1", version 2 = "1.1"
Output: -1

Example 2:
Input: version1 = "1.0.1", version2 = "1"
Output: 1

Example 3:
Input: version1 = "7.5.2.4", version2 = "7.5.3"
Output: -1

--

**Comment by anupsingh0512** [comment]
compare  function(A, B)
         {	   
	  A = A.split('.');
	  B = B.split('.');
	  var i = 0;
	  while (i <A.length || i <B.length)
           {
	      if(i <A.length && i < B.length)
                {
	          if(parseInt(A[i]) > parseInt(B[i]))
                   {
	              return 1;
	          }
                 else if(parseInt(A[i]) < parseInt(B[i]))
                 {
	              return -1;
	          }
	         } 
               else if(i < A.length && i >= B.length)
                {
	          if(parseInt(A[i]) > 0)
                   {
	              return 1;
	          } 
              else 
              {
	         return 0;
	          }
	      }
             else if(i >= A.length && i < B.length)
              {
	          if(parseInt(B[i]) > 0){
	              return -1
	          } else {
	              return 0;
	          }
	      }
	      i++;
	  } 
	  return 0;
	}

**Comment by anupsingh0512** [comment]
Hi Rajesh,

I have tried the above use case .Please Check.

Regards,
Anup
